### ISSUE TITLE
Error during deploy: [fog][WARNING] 'mime-types' missing, please install and try again.

### ISSUE THREAD

**Issue by macandcheese** [fredjean/middleman-s3_sync#123]
Just recently started receiving this error. Tried re-installing fog and mime-type gems, no luck.

Full output: 

> $ exec middleman s3_sync
> WARN: Unresolved specs during Gem::Specification.reset:
>       parallel (>= 0)
>       minitest (~> 5.1)
>       padrino-helpers (~> 0.13.0)
>       addressable (~> 2, ~> 2.3)
>       listen (~> 3.0.0)
>       sass (>= 3.4)
>       hashie (~> 3.4)
>       concurrent-ruby (~> 1.0)
> WARN: Clearing out unresolved specs.
> Please report a bug if this causes problems.
> == Instrument (sitemap.manipulator): 1253.158ms
> {:name=>:collections}
> == Instrument (sitemap.update): 1341.1850000000002ms
> {:reasons=>[:touched_file, :registered_new_manipulator_front_matter, :registered_new_manipulator_sitemap_ondisk, :registered_new_manipulator_sitemap_import, :registered_new_manipulator_sitemap_endpoint, :registered_new_manipulator_sitemap_proxies, :registered_new_manipulator_sitemap_redirects, :registered_new_manipulator_sitemap_move_files, :registered_new_manipulator_sitemap_ignore, :registered_new_manipulator_routing, :registered_new_manipulator_collections, :registered_new_manipulator_s3_sync]}
>      s3_sync  Let's see if there's work to be done...
> [fog][WARNING] 'mime-types' missing, please install and try again.                                                                                        | Time: 00:00:00
> 
> [Process completed]

**Comment by fredjean** [comment]
I am sorry if I sound cranky, but I have many issues opened around this and pulled in the fog developers more than once. What you are seeing is caused by [this issue](https://github.com/fog/fog/issues/3775).  Please raise an issue with the fog project since this is where the root cause is.

You might be OK if you add the `mime-types` gem to your Gemfile. You might not. I have already tried what I could to try to insulate users from this issue.

If you insist on having me look into this any further, provide a sanitized `config.rb` file, `Gemfile` and `Gemfile.lock`.

**Comment by macandcheese** [comment]
Appreciate the response, adding

> `gem 'mime-types'`

as a dependency in config.rb worked for me. 
I hadn't updated any project dependencies so it's strange the error only cropped up recently. 
Thanks again.

**Comment by Stono** [comment]
The additional gem worked for me too..
