### ISSUE TITLE
Times shown when syncing are unclear

### ISSUE THREAD

**Issue by whitmanc** [fredjean/middleman-s3_sync#125]
Thanks for the great gem - working like a charm. Noticed one obscurity, though, when running `middleman s3_sync` some times are shown that don't make much sense to me. Please see screenshot

<img width="1128" alt="screen shot 2016-05-20 at 12 53 10 pm" src="https://cloud.githubusercontent.com/assets/1023159/15440394/11408c1e-1e8a-11e6-8700-c2e6adf83833.png">

**Comment by fredjean** [comment]
The main goal here is to show that something is happening since it takes a while to evaluate the resources to see whether they need to be sync'ed. The time displayed is a very loose estimation of the time remaining to complete the task. They should be taken about as seriously as any other progress bar.

**Comment by whitmanc** [comment]
@fredjean Thanks for following up & got it. It definitely serves it's intended purpose, and I bet it is more useful for larger projects.
