### ISSUE TITLE
AWS permission requirements

### ISSUE THREAD

**Issue by ebfg** [fredjean/middleman-s3_sync#63]
We're crafting an IAM user policy for use with this plugin. We weren't able to get it to work until we gave the IAM user read access to all buckets in our account. Write access is only required for the configured bucket. It seems like read should be similarly  restricted.

**Comment by stoplion** [comment]
Doesn't policy need a `Principal`?

**Comment by fredjean** [comment]
@stoplion It depends on how the policy is defined in IAM. In my case, I use the AWS Management Console to create a group for the IAM users who can push to my bucket and created the policy directly with the group. I don't have to specify the Principal in this case.

Using the IAM APIs will probably require you to specify a Principal since there isn't a context for the policy itself.
